---
# handlers file for RoleCentOS
- name: restart server
  reboot:
    msg: "Reboot init by Ansible"
    connect_timeout: 5
    reboot_timeout: 60
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
